### ISSUE TITLE
Xamarin.Kotlin.StdLib version works from (>= 1.5.31.1)

### ISSUE THREAD

**Issue by NishiokaTakeo** [jedusei/Twilio.Conversations.Xamarin#6]
Hi,

As part of the [conversation](https://github.com/jedusei/Twilio.Conversations.Xamarin/issues/3), I forgot to mention. 

One of the Twilio.Conversations.Xamarin 's dependences, [Xamarin.Kotlin.StdLib] (>= 1.5.31) 
 will be trouble to initialise IConversationClient. 

I have upgraded to [Xamarin.Kotlin.StdLib] (>= 1.5.31.1) then it became working fine. It might be good to update to version description in the dependency section in [nuget package page](https://www.nuget.org/packages/Twilio.Conversations.Xamarin/#dependencies-body-tab). 

Or I will do if I know how to do that :)

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

Thank you for pointing this out. Can you post the error you get when initialising the client with Xamarin.Kotlin.StdLib 1.5.31 installed?

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Yes. It causes at `IConversationsClient.CreateAsync(context, token, properties);`

The error was 
```
`{Java.Lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/JvmClassMappingKt; ---> Java.Lang.ClassNotFoundException: Didn't find class "kotlin.jvm.JvmClassMappingKt" on path: DexPathList[[zip file "/data/app/com.companyname.app1-1/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.app1-1/lib/x86_64, /vendor/lib64, /system/lib64]]`
```

The stack trace is below. Sorry for ugly text.
```
--- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12890 
  at Android.Runtime.JNIEnv.FindClass (System.String classname) [0x0004c] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:572 
  at Twilio.Conversations.IConversationsClient..cctor () [0x00000] in C:\Users\Joe\source\repos\Twilio.Conversations.Xamarin\Twilio.Conversations.Droid\Additions\Fixes\IConversationsClient.cs:14 
  --- End of managed Java.Lang.NoClassDefFoundError stack trace ---
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/JvmClassMappingKt;
	at com.twilio.conversations.ConversationsClientImpl.<clinit>(ConversationsClientImpl.java:66)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:309)
	at crc64a7a6b04b89628087.MainActivity.n_onCreate(Native Method)
	at crc64a7a6b04b89628087.MainActivity.onCreate(MainActivity.java:37)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.JvmClassMappingKt" on path: DexPathList[[zip file "/data/app/com.companyname.app1-1/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.app1-1/lib/x86_64, /vendor/lib64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 18 more
	Suppressed: java.lang.ClassNotFoundException: kotlin.jvm.JvmClassMappingKt
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 19 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
}
```

**Comment by jedusei** [comment]
Thanks very much @NishiokaTakeo 

I didn't encounter this error during my tests, but I can see that there have been some minor patches to version 1.5.31 of Xamarin.Kotlin.Stdlib package, and the last patch is [1.5.31.4](https://www.nuget.org/packages/Xamarin.Kotlin.StdLib/1.5.31.4), so I think it's best to upgrade to that.

Can you please install Xamarin.Kotlin.StdLib 1.5.31.4 and let me know whether you encounter any errors?

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

I have checked with version 1.5.31.4,  and it does not encounter the errors.  I have received `Completed `status in `OnClientSynchronization()`.

**Comment by jedusei** [comment]
Thank you @NishiokaTakeo 
I'll upgrade the dependency in the next release.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

Thank you very much :)
